inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 150
Metrics/BlockLength:
  Max: 50
Metrics/MethodLength:
  Max: 240
Metrics/AbcSize:
  Max: 160
Metrics/ClassLength:
  Max: 300
Style/Next:
  Enabled: false
Style/Documentation:
  Enabled: false
